In [4]:
import numpy as np
#Crear una matriz 3x3 con valores del 0 al 8
x1 = np.arange(0,9,1)
print(x1)
x2 = x1.reshape(3,3)
print(x2)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#2) Crear una matriz de identidad de 3x3
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#3. Utilizar numpy para geneara un numero aleatorio entre 0 y 1
num = np.random.rand()
print(num)

0.536106858226516


In [17]:
#4. Utilizar numpy para generar un arreglo de 25 numeros aleatorioas con una   distribucion normal
x = np.random.rand(25)
print(x)

[0.5321378  0.5262899  0.67618347 0.41433441 0.50842041 0.52647692
 0.60561201 0.79341133 0.44113622 0.07146382 0.16078998 0.02142875
 0.11114161 0.78319644 0.83275674 0.65994717 0.10625294 0.0566114
 0.82054291 0.96325165 0.91931977 0.45078698 0.86180051 0.42064015
 0.01338721]


In [18]:
#5. Crear la siguiente matriz
z1 = np.arange(1,101) /100
y1 = z1.reshape(10,10)
print(y1)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [14]:
#6. Crear un arreglo de 20 valores lineales entre 0 y 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])